#pragma once

#define IDI_ICON1 1
#define IDI_ICON2 2
#define IDI_ICON3 3
#define IDI_ICON4 4
#define IDI_ICON5 5

#define APP_VERSION 7,3,2,0
#define STR_APP_VERSION L"7.3.2.0"
#define STR_APP_DESCRIPTION L"An application for shutting down the system"
#define STR_APP_NAME L"Shutdown Windows"
#define STR_APP_EXE_NAME L"Shutdown.exe"

// Main Window

#define ID_ACTION_SHUTDOWN 0
#define ID_ACTION_REBOOT 1
#define ID_ACTION_LOGOFF 2
#define ID_ACTION_LOCK 3
#define ID_ACTION_CANCEL 4

#define ACTION_SHUTDOWN L"Shutdown"
#define ACTION_REBOOT L"Rebooting"
#define ACTION_LOGOFF L"Logging off"
#define ACTION_LOCK L"Locking"
#define ACTION_CANCEL L"Canceling"

#define IDC_APP_CLASS 100
#define IDS_APP_TITLE 101
#define IDS_ACTION_STATIC_TITLE 102
#define IDS_ACTIONS_COMBOBOX_TITLE 103
#define IDS_EXECACTION_BUTTON_TITLE 104
#define IDS_COMPUTERS_STATIC_TITLE 105
#define IDS_COMPUTERS_EDIT_TITLE 106
#define IDS_ADDCOMPUTERS_BUTTON_TITLE 107
#define IDS_REMOVECOMPUTERS_BUTTON_TITLE 108
#define IDS_CLEARCOMPUTERS_BUTTON_TITLE 109
#define IDS_TIMER_STATIC_TITLE 110
#define IDS_TIMER_EDIT_TITLE 111
#define IDS_TIMER_DEF_BUTTON_TITLE 112
#define IDS_FORCE_CHECKBOX_TITLE 113
#define IDS_PLANNED_CHECKBOX_TITLE 114
#define IDS_MESSAGE_STATIC_TITLE 115
#define IDS_MESSAGE_EDIT_TITLE 116

#define STR_APP_CLASS L"ShutdownClassName"
#define STR_APP_TITLE L"Shutdown Windows"
#define STR_ACTION_STATIC_TITLE L"Select action"
#define STR_ACTIONS_COMBOBOX_TITLE NULL
#define STR_EXECACTION_BUTTON_TITLE L"Execute"
#define STR_COMPUTERS_STATIC_TITLE L"List of computers"
#define STR_ADDCOMPUTERS_BUTTON_TITLE L"Add"
#define STR_REMOVECOMPUTERS_BUTTON_TITLE L"Remove"
#define STR_CLEARCOMPUTERS_BUTTON_TITLE L"Clear"
#define STR_COMPUTERS_EDIT_TITLE NULL
#define STR_TIMER_STATIC_TITLE L"Time-out period in seconds"
#define STR_TIMER_EDIT_TITLE L"120"
#define STR_TIMER_DEF_BUTTON_TITLE L"Default"
#define STR_FORCE_CHECKBOX_TITLE L"Force apps to close"
#define STR_PLANNED_CHECKBOX_TITLE L"Planned break"
#define STR_MESSAGE_STATIC_TITLE L"Warning message"
#define STR_MESSAGE_EDIT_TITLE NULL

#define IDS_FILE_POPUP_MENU 200
#define IDS_SYSTEMDIALOG_POPUP_ITEM 208
#define IDS_EXIT_POPUP_ITEM 209
#define IDS_HELP_POPUP_MENU 290
#define IDS_ABOUT_POPUP_ITEM 299

#define STR_FILE_POPUP_MENU L"File"
#define STR_SYSTEMDIALOG_POPUP_ITEM L"System Dialog"
#define STR_EXIT_POPUP_ITEM L"Exit"
#define STR_HELP_POPUP_MENU L"Help"
#define STR_ABOUT_POPUP_ITEM L"About"

// Add Computers Dialog

#define IDC_ADDCOMPUTERS_DIALOG_CLASS 900
#define IDS_ADDCOMPUTERS_DIALOG_TITLE 901
#define IDS_ADDCOMPUTERS_COMPUTERNAME_STATIC 902
#define IDS_ADDCOMPUTERS_COMPUTERNAME_EDIT 903
#define IDS_ADDCOMPUTERS_ADD_BUTTON 904
#define IDS_ADDCOMPUTERS_CANCEL_BUTTON 905

#define STR_ADDCOMPUTERS_DIALOG_CLASS L"AddComputersDialogClassName"
#define STR_ADDCOMPUTERS_DIALOG_TITLE L"Add computer"
#define STR_ADDCOMPUTERS_COMPUTERNAME_STATIC L"Enter computer name"
#define STR_ADDCOMPUTERS_COMPUTERNAME_EDIT NULL
#define STR_ADDCOMPUTERS_ADD_BUTTON L"Add"
#define STR_ADDCOMPUTERS_CANCEL_BUTTON L"Cancel"
